### ISSUE TITLE
JSSv3: Discuss/identify governance views that are missing in Pioneer and could be feasibly, quickly and easily created.

### ISSUE THREAD

**Issue by mochet** [Joystream/community-repo#794]
SSIA
* `Governance views` = any and all views of any data generated by the Joystream platform, whether they be of interest to casual observers, content creators, WG leads, WG workers, validators/nominators or council members. It basically means `anyone & everyone`.
* This can start life as a very basic table/database, to try and build knowledge and deliverables on what we anticipate or know the community would like to see.
* It can really just be a building block and can be improved upon at later stages

But to create a general list of
- known things that are missing currently
- whether it is percieved that they are likely to be delivered upon mainnet launch
- consider particular Joystream aspects such as NFT marketplace, Bounties, Forum, Staking/Burning

## Tasks
- [ ] Create a basic table containing
	1. [ ] Basic description
	2. [ ] The product where someone would ideally expect to see it (Pioneer, Atlas or solely `JSSv3` or all 3)
	3. [ ] Link(s) to any known relevant issues
	4. [ ] How it should be presented (`Table`, `text searchable`, `time viewable`, `Charts/visualizations`, `individual user view`)
	5. [ ] The scope (`FM Program`, `DAO Health`, `User rewards`, `Tokenomics` etc)
	6. [ ] Any potential roadblocks (i.e. `Bounty Module won't be present`)
	7. [ ] Expected data sources (`Query Node`, `Joystreamstats` (i.e. grading script outputs), `RPC`, `Joystream Storage/Distributor network`, `Airtable`, `Notion`)
	8. [ ] Expected difficulty (`High`, `Moderate`, `Low`)
	9. [ ] Impact/importance (`Essential`, `High`, `Medium`, `Low`)
- [ ] Ask for community input and maintain a live list

**Comment by traumschule** [comment]
Please reopen on pioneer repo if needed.
