### ISSUE TITLE
Exchange Research

### ISSUE THREAD

**Issue by mochet** [Joystream/community-repo#865]
AFAIK no one has really looked into exchanges/DeFi/places to list Joystream. This seems like a perfect task to put onto the forums and crowdsource research for from the community.

I plan on spearheading this and tipping useful contributors with my own personal $JOY at this stage. I wouldn't be seeking any funding/council approvals for any of this activity at this stage.

## Todo
- [ ] List out viable exchanges, whether they already support any substrate projects, links to submit coins for consideration, any requirements they may have for listing, maybe list out additional things like what country they operate from. Also whether they are centralized/decentralized would be very useful to know.
- [ ] Put together a good copy/paste explanation of the project, community and value of the project to send to potential exchanges
- [ ] Fill in submission forms and ensure whoever does this will be around to reply to emails or anything else that is needed

**Comment by mochet** [comment]
The written introduction for the project will probably also be crowdsourced via forums. This should technically be the responsibility of the marketing WG but I would expect it to take some time for that WG to get up and running.

The written description of the project for this specific initiative will need to be tailored to make the project as attractive as possible to exchanges.

**Comment by adovrodion** [comment]
Can we contact the exchanges that invested in Joystream? - OKX, MEXC, Gate
It may be easier to negotiate with them, because it is in their own interest to list JOY, since they also have JOY tokens.

MEXC Platform Project Listing Application - https://docs.google.com/forms/d/e/1FAIpQLSeRsOYxe7TvVarU6TUtFCf3GISrYtPguTiaA61pi6u_fzM9VQ/viewform (Thanks @0x2bc for the link)

**Comment by 0x2bc** [comment]
FYI Listing Strategy (draft v1)
 https://github.com/0x2bc/community-repo/blob/master/community-roadmap/ListingStrategy.md

**Comment by adovrodion** [comment]
If necessary, I am also ready to allocate part of my JOY

**Comment by traumschule** [comment]
There's now a multi-sig address under control of @0x2bc and @mochet to fund this endeavor (research / listing):
`j4WdqBXg95Cipqu8wVzKvTTf3WGSzE1cEHEjt7P6Ed2AthZAA` 
Brief intro: [Working With Multi-Sig Accounts](https://pioneerapp.xyz/#/forum/thread/7)

**Comment by 0x2bc** [comment]
my pre proposal on Exchange Research https://pioneerapp.xyz/#/forum/thread/28

**Comment by chrlschwb** [comment]
Where can I see the updates after the last entry here?
